[package]
name = "dla-cover-cache"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
dla-application.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
ureq.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile = "=3.27.0"
